# Generated by Django 4.1.7 on 2023-10-10 20:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_lecture_likelecture_studentquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('lecture', models.CharField(blank=True, max_length=100)),
                ('money', models.IntegerField(blank=True, default='0')),
                ('wallet', models.IntegerField(blank=True, default='0')),
                ('value', models.IntegerField(blank=True, default='0', null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('charge', 'Charge'), ('purchase', 'Purchase')], max_length=25, null=True)),
                ('purchase_type', models.CharField(blank=True, choices=[('code', 'Code'), ('wallet', 'Wallet')], max_length=25)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='lesson_name',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='liker',
            new_name='second_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='username',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('charge', 'Charge'), ('purchase', 'Purchase'), ('withdraw', 'Withdraw'), ('like', 'Like'), ('buy', 'Buy'), ('comment', 'Comment'), ('reply', 'Reply')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
