# Generated by Django 4.1.7 on 2023-10-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transaction_delete_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to='profile_images'),
        ),
    ]
