# Generated by Django 4.1.7 on 2023-10-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='blank-profile-picture.jpg', null=True, upload_to='profile_images'),
        ),
    ]
