# Generated by Django 4.1.7 on 2023-10-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_logininfo_username_alter_logininfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logininfo',
            name='username',
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
