# Generated by Django 4.1.7 on 2023-10-14 10:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_buylesson_lecture_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentLectureObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(default='none.jpeg', upload_to='lecture_images')),
                ('price', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Lecture Object',
                'verbose_name_plural': 'Student Lecture Objects',
            },
        ),
    ]
