# Generated by Django 4.1.7 on 2023-10-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_lecture_duration_studentlectureobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlectureobject',
            name='lecture_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
