# Generated by Django 4.1.7 on 2023-10-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_studentlectureobject_lecture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlectureobject',
            name='year',
            field=models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], default='first', max_length=25),
        ),
    ]
