# Generated by Django 4.1.7 on 2023-10-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_studentlectureobject_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(default='blank-lecture.jpeg', upload_to='lecture_images'),
        ),
    ]
