# Generated by Django 4.1.7 on 2023-10-14 20:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_code_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlectureobject',
            old_name='id',
            new_name='object_id',
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('view_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('student_part_object_id', models.CharField(max_length=500)),
                ('part_id', models.CharField(max_length=500)),
                ('lecture_id', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPartObject',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('part_id', models.CharField(max_length=500)),
                ('lecture_id', models.CharField(max_length=500)),
                ('assignment_id', models.CharField(blank=True, max_length=500)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('part_number', models.IntegerField(default=1)),
                ('type', models.CharField(blank=True, choices=[('video', 'Video'), ('link', 'Link'), ('assignment', 'Assignment')], max_length=25)),
                ('video', models.FileField(blank=True, upload_to='lectures')),
                ('video_url', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
