# Generated by Django 4.1.7 on 2023-10-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_id_studentlectureobject_object_id_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlectureobject',
            name='image',
            field=models.ImageField(default='blank-lecture.jpeg', upload_to='lecture_images'),
        ),
    ]
