# Generated by Django 4.1.7 on 2023-10-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_studentlectureobject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlectureobject',
            name='object',
            field=models.BooleanField(default=True),
        ),
    ]
