# Generated by Django 4.1.7 on 2023-10-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_studentlectureobject_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('link', 'Link'), ('assignment', 'Assignment'), ('file', 'File')], max_length=25),
        ),
        migrations.AlterField(
            model_name='studentpartobject',
            name='type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('link', 'Link'), ('assignment', 'Assignment'), ('file', 'File')], max_length=25),
        ),
    ]
