# Generated by Django 4.1.7 on 2023-10-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_part_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
