# Generated by Django 4.1.7 on 2023-10-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_part_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='views_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentpartobject',
            name='views_limit',
            field=models.IntegerField(default=0),
        ),
    ]
