# Generated by Django 4.1.7 on 2023-10-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_part_active_studentpartobject_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='video',
        ),
    ]
