# Generated by Django 4.1.7 on 2023-10-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_lecture_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='year',
            field=models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], max_length=25, null=True),
        ),
    ]
