# Generated by Django 4.1.7 on 2023-10-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_part_visible_part_youtube_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpartobject',
            name='active',
        ),
        migrations.RemoveField(
            model_name='studentpartobject',
            name='link',
        ),
        migrations.RemoveField(
            model_name='studentpartobject',
            name='video',
        ),
        migrations.RemoveField(
            model_name='studentpartobject',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='studentpartobject',
            name='youtube_url',
        ),
    ]
