# Generated by Django 4.1.7 on 2023-10-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_studentpartobject_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buylesson',
            name='method',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('code', 'Code'), ('lecture_code', 'Lecture Code'), ('chapter', 'Chapter'), ('group', 'Group'), ('admin', 'Addmin'), ('link', 'Link')], default='code', max_length=25),
        ),
    ]
