# Generated by Django 4.1.7 on 2023-10-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_part_created_at_studentpartobject_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='original',
            field=models.BooleanField(default=True),
        ),
    ]
