# Generated by Django 4.1.7 on 2023-10-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_lecturecode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturecode',
            old_name='total_students',
            new_name='total_students_number',
        ),
    ]
