# Generated by Django 4.1.7 on 2023-10-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_total_students_lecturecode_total_students_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylesson',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
