# Generated by Django 4.1.7 on 2023-10-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_buylesson_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlectureobject',
            name='parts_number',
            field=models.IntegerField(default=0),
        ),
    ]
