# Generated by Django 4.1.7 on 2023-10-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_studentpartobject_part_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='assignment_questions_number',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='studentpartobject',
            name='assignment_questions_number',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
