# Generated by Django 4.1.7 on 2023-10-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_part_assignment_questions_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpartobject',
            name='assignment_user_percentage',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
