# Generated by Django 4.1.7 on 2023-10-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_studentpartobject_assignment_user_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='assignment_total_applicants',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='studentpartobject',
            name='assignment_total_applicants',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
