# Generated by Django 4.1.7 on 2023-10-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_part_assignment_questions_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentopen',
            name='timer',
        ),
        migrations.AddField(
            model_name='assignment',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentopen',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentopen',
            name='timer_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentopen',
            name='timer_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
