# Generated by Django 4.1.7 on 2024-01-06 17:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0041_remove_assignmentopen_timer_assignment_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('number', models.IntegerField(default=1)),
                ('logo_title', models.CharField(blank=True, max_length=500)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logo_images')),
                ('primary_color', models.CharField(blank=True, max_length=500)),
                ('secondary_color', models.CharField(blank=True, max_length=500)),
                ('home_page_image_1', models.ImageField(blank=True, null=True, upload_to='theme_images')),
                ('home_page_image_2', models.ImageField(blank=True, null=True, upload_to='theme_images')),
                ('home_page_image_3', models.ImageField(blank=True, null=True, upload_to='theme_images')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
