# Generated by Django 4.1.7 on 2024-01-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='logo_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=25, null=True),
        ),
    ]
