# Generated by Django 4.1.7 on 2024-01-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_theme_logo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
