# Generated by Django 4.1.7 on 2024-03-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_theme_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturecode',
            name='qr_code',
            field=models.ImageField(default='blank-lecture.jpeg', upload_to='qr-codes'),
        ),
    ]
