# Generated by Django 4.1.7 on 2024-04-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_lecturecode_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlectureobject',
            name='finish_at',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentlectureobject',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
