# Generated by Django 4.1.7 on 2024-04-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_studentlectureobject_finish_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlectureobject',
            name='finish_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
