# Generated by Django 4.1.7 on 2024-04-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_studentlectureobject_finish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlectureobject',
            name='finish_at',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
