# Generated by Django 4.1.7 on 2024-07-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_studentlectureobject_finish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylesson',
            name='serial',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
