# Generated by Django 4.1.7 on 2024-07-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_buylesson_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_of_sells',
            field=models.IntegerField(default=0),
        ),
    ]
