# Generated by Django 4.1.7 on 2024-07-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_lecture_year_alter_studentlectureobject_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='lecture',
            new_name='item_id',
        ),
    ]
