# Generated by Django 4.1.7 on 2024-07-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_rename_lecture_transaction_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='item_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
