# Generated by Django 4.1.7 on 2024-07-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_platformsettings_image_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='text_logo',
            field=models.CharField(blank=True, default='Teacher Name', max_length=100),
        ),
    ]
