# Generated by Django 4.1.7 on 2024-07-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_platformsettings_text_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
