# Generated by Django 4.1.7 on 2024-07-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_platformsettings_facebook_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformsettings',
            old_name='facebook_link',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
