# Generated by Django 4.1.7 on 2024-07-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='youtube',
        ),
    ]
