# Generated by Django 4.1.7 on 2024-07-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_remove_sociallink_telegram_remove_sociallink_tiktok_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='money',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='purchase_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('purchase', 'Purchase')], max_length=25, null=True),
        ),
    ]
