# Generated by Django 4.1.7 on 2024-07-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_remove_notification_money_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='lecture',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply')], max_length=25, null=True),
        ),
    ]
