# Generated by Django 4.1.7 on 2024-07-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_remove_notification_lecture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplecture',
            name='teacher_img',
        ),
        migrations.RemoveField(
            model_name='grouplecture',
            name='teacher_name',
        ),
    ]
