# Generated by Django 4.1.7 on 2024-07-31 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_remove_grouplecture_teacher_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
