# Generated by Django 4.1.7 on 2024-07-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_remove_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplecture',
            name='no_of_students',
            field=models.IntegerField(default=0),
        ),
    ]
