# Generated by Django 4.1.7 on 2024-07-31 19:34

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_grouplecture_no_of_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group_id', models.CharField(blank=True, max_length=100)),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='groups_images')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Group Message',
                'verbose_name_plural': 'Group Messages',
            },
        ),
    ]
