# Generated by Django 4.1.7 on 2024-07-31 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0069_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
