# Generated by Django 4.1.7 on 2024-08-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_groupmessage_user_groupmessage_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='qr_code',
            field=models.ImageField(default='blank-lecture.jpeg', upload_to='qr-codes'),
        ),
    ]
