# Generated by Django 4.1.7 on 2024-08-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_group_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='group_image',
        ),
    ]
