# Generated by Django 4.1.7 on 2024-08-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_groupmessage_message_image_alter_groupmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='method',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('code', 'Code'), ('qr_code', 'Qr Code'), ('link', 'Link')], default='admin', max_length=25),
        ),
    ]
