# Generated by Django 4.1.7 on 2024-08-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_groupmember_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplecture',
            name='no_of_students',
        ),
    ]
