# Generated by Django 4.1.7 on 2024-08-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_remove_grouplecture_no_of_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='no_of_messages',
            field=models.IntegerField(default=0),
        ),
    ]
