# Generated by Django 4.1.7 on 2024-08-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_group_no_of_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='last_message',
            new_name='last_update',
        ),
    ]
