# Generated by Django 4.1.7 on 2024-08-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_rename_last_message_group_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='new_lectures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='new_messages',
            field=models.IntegerField(default=0),
        ),
    ]
