# Generated by Django 4.1.7 on 2024-08-02 20:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0078_groupmember_new_lectures_groupmember_new_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group_id', models.CharField(blank=True, max_length=100)),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(default='blank-profile-picture.png', upload_to='group_images')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('reply_time', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Request',
                'verbose_name_plural': 'Group Requests',
            },
        ),
    ]
