# Generated by Django 4.1.7 on 2024-08-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_grouprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprequest',
            name='reply',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
