# Generated by Django 4.1.7 on 2024-08-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_grouprequest_reply_alter_grouprequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='no_of_requests',
            field=models.IntegerField(default=0),
        ),
    ]
