# Generated by Django 4.1.7 on 2024-08-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_group_no_of_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='method',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('code', 'Code'), ('qr_code', 'Qr Code'), ('link', 'Link'), ('request', 'Request')], default='admin', max_length=25),
        ),
    ]
