# Generated by Django 4.1.7 on 2024-08-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_alter_groupmember_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentopen',
            old_name='minutes',
            new_name='remain_minutes',
        ),
        migrations.RemoveField(
            model_name='assignmentopen',
            name='timer_minutes',
        ),
        migrations.RemoveField(
            model_name='assignmentopen',
            name='timer_seconds',
        ),
    ]
