# Generated by Django 4.1.7 on 2024-08-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_rename_minutes_assignmentopen_remain_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions-images'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('q_choices', 'Q Choices'), ('writing', 'Writing')], default=[('q_choices', 'Q Choices'), ('writing', 'Writing')], max_length=25, null=True),
        ),
    ]
