# Generated by Django 4.1.7 on 2024-08-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_alter_question_question_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions-images'),
        ),
    ]
