# Generated by Django 4.1.7 on 2024-08-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_alter_answer_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_type',
            field=models.CharField(choices=[('q_choices', 'Q Choices'), ('writing', 'Writing')], default=[('q_choices', 'Q Choices'), ('writing', 'Writing')], max_length=25),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('q_choices', 'Q Choices'), ('writing', 'Writing')], default=[('q_choices', 'Q Choices'), ('writing', 'Writing')], max_length=25),
        ),
    ]
