# Generated by Django 4.1.7 on 2024-08-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_answer_question_type_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='writing_answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
