# Generated by Django 4.1.7 on 2024-08-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_question_writing_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='writing_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='writing_answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
