# Generated by Django 4.1.7 on 2024-08-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_remove_question_writing_answer_answer_writing_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmit',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
