# Generated by Django 4.1.7 on 2024-08-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_alter_answer_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='minutes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentopen',
            name='remain_minutes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
