# Generated by Django 4.1.7 on 2024-08-10 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_alter_assignment_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentopen',
            old_name='remain_minutes',
            new_name='remain_secs',
        ),
    ]
