# Generated by Django 4.1.7 on 2024-08-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_rename_remain_minutes_assignmentopen_remain_secs'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmit',
            name='assignment_duration',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
