# Generated by Django 4.1.7 on 2024-08-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_assignmentsubmit_assignment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmit',
            name='true_answers_percent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
