# Generated by Django 4.1.7 on 2024-08-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_assignmentsubmit_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmit',
            name='assignment_type',
            field=models.CharField(blank=True, choices=[('test', 'Test'), ('homework', 'Homework')], max_length=25),
        ),
    ]
