# Generated by Django 4.1.7 on 2024-08-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_assignmentsubmit_lecture_id_assignmentsubmit_part_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='website_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
