# Generated by Django 4.1.7 on 2024-08-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_platformsettings_website_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentquestion',
            old_name='comment_id',
            new_name='question_id',
        ),
        migrations.RemoveField(
            model_name='studentquestion',
            name='commented_to',
        ),
    ]
