# Generated by Django 4.1.7 on 2024-08-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_rename_comment_id_studentquestion_question_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentquestion',
            old_name='comment',
            new_name='question',
        ),
    ]
