# Generated by Django 4.1.7 on 2024-08-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_rename_comment_studentquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
