# Generated by Django 4.1.7 on 2024-08-22 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_studentquestion_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestionanswer',
            name='answered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
