# Generated by Django 4.1.7 on 2024-08-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_alter_studentquestionanswer_answered_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentquestionanswer',
            old_name='answered_to',
            new_name='answered_to_profile',
        ),
    ]
