# Generated by Django 4.1.7 on 2024-08-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_rename_answered_to_studentquestionanswer_answered_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='replyed',
            field=models.BooleanField(default=False),
        ),
    ]
