# Generated by Django 4.1.7 on 2024-08-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_studentquestion_replyed'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestionanswer',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
