# Generated by Django 4.1.7 on 2024-08-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_remove_studentquestionanswer_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturediscount',
            name='discount_value',
            field=models.IntegerField(default=0),
        ),
    ]
