# Generated by Django 4.1.7 on 2024-08-24 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_lecturediscount_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturecode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='lecturediscount',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
