# Generated by Django 4.1.7 on 2024-08-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_lecturecode_expired_at_lecturediscount_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buylesson',
            name='method',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('code', 'Code'), ('lecture_code', 'Lecture Code'), ('chapter', 'Chapter'), ('group', 'Group'), ('admin', 'Admin'), ('link', 'Link'), ('wallet_discount', 'Wallet Discount')], default='code', max_length=25),
        ),
    ]
