# Generated by Django 4.1.7 on 2024-08-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_alter_buylesson_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('code', 'Code'), ('wallet', 'Wallet'), ('wallet_discount', 'Wallet Discount')], max_length=25),
        ),
    ]
