# Generated by Django 4.1.7 on 2024-08-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_assignment_part_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='award_discount_value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='award_lecture_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='award_percentage_needed',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
