# Generated by Django 4.1.7 on 2024-08-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_assignment_award_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='award_system',
            field=models.BooleanField(default=False),
        ),
    ]
