# Generated by Django 4.1.7 on 2024-08-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_assignment_award_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturediscount',
            name='type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('assignment_reward', 'Assignment Reward')], max_length=25),
        ),
    ]
