# Generated by Django 4.1.7 on 2024-08-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0115_lecturediscount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturediscount',
            name='assignment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
