# Generated by Django 4.1.7 on 2024-08-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_lecturediscount_assignment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturediscount',
            name='awarded_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
