# Generated by Django 4.1.7 on 2024-08-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_assignmentsubmit_award_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmit',
            name='award_discount',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
