# Generated by Django 4.1.7 on 2024-08-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_assignmentsubmit_award_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdf-files'),
        ),
    ]
