# Generated by Django 4.1.7 on 2024-08-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_part_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='pdf_file_pages_number',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
